export const newsLetterMockData = [
    {
        id: 1,
        subject: "john.doe@example.com",
        send_date: "2024-02-20",
        status: "Verified",
        venues: "Last Opened: 2024-02-25",
    },
    {
        id: 2,
        subject: "jane.smith@example.com",
        send_date: "2024-02-18",
        status: "Unverified",
        venues: "Last Opened: 2024-02-22",
    },
    {
        id: 3,
        subject: "michael.brown@example.com",
        send_date: "2024-02-25",
        status: "Verified",
        venues: "Last Opened: 2024-02-26",
    },
    {
        id: 4,
        subject: "sarah.white@example.com",
        send_date: "2024-02-10",
        status: "Unverified",
        venues: "Last Opened: 2024-02-15",
    },
    {
        id: 5,
        subject: "david.johnson@example.com",
        send_date: "2024-02-05",
        status: "Unverified",
        venues: "Last Opened: 2024-02-10",
    },
    {
        id: 6,
        subject: "emma.wilson@example.com",
        send_date: "2024-02-12",
        status: "Verified",
        venues: "Last Opened: 2024-02-18",
    },
    {
        id: 7,
        subject: "oliver.miller@example.com",
        send_date: "2024-02-14",
        status: "Verified",
        venues: "Last Opened: 2024-02-16",
    },
    {
        id: 8,
        subject: "charlotte.lee@example.com",
        send_date: "2024-02-17",
        status: "Unverified",
        venues: "Last Opened: 2024-02-20",
    },
    {
        id: 9,
        subject: "william.martin@example.com",
        send_date: "2024-02-22",
        status: "Verified",
        venues: "Last Opened: 2024-02-25",
    },
    {
        id: 10,
        subject: "amelia.thomas@example.com",
        send_date: "2024-02-28",
        status: "Unverified",
        venues: "Last Opened: 2024-02-29",
    },
];
