image: node:18

options:
  max-time: 20

pipelines:
  default:
    - step:
        name: Run Tests & Coverage
        caches:
          - node
        script:
          # Make your script executable
          - chmod +x test/scripts/run-tests.sh

          # Run your custom test script
          - ./test/scripts/run-tests.sh

        artifacts:
          - coverage/**