image: node:18

pipelines:
  branches:
    feature/**:
      - step:
          name: Build Tasks & Coverage
          size: 2x
          caches:
            - node
          script:
            - echo "Task_Info- Keeping_Back-lash_k_Coverage"
            # apt-get update && apt-get install -y tar
            # Check Node & npm versions
            - node -v && npm -v
            # Check if lock file exists (use either yarn.lock or package-lock.json)
            - |
              if [ -f "yarn.lock" ]; then
                echo "Using yarn"
                yarn install
              elif [ -f "package-lock.json" ]; then
                echo "Using npm"
                npm ci
              else
                echo "No lock file found"
                npm install
              fi
            # Run user jest scripts
            - echo "RUNNING test scripts STARTING"
            - npm run test
