export const movieScreensMockData = [
    {
        key: "1",
        screen_name: "IMAX Screen 1",
        theater: "Madison Square Cinema, NY",
        total_seats: 250,
        available_seats: 120,
        show_time: "2024-12-30 18:00",
        status: "Available",
    },
    {
        key: "2",
        screen_name: "Dolby Atmos Screen",
        theater: "Silicon Valley Multiplex, CA",
        total_seats: 180,
        available_seats: 50,
        show_time: "2024-11-15 10:30",
        status: "Almost Full",
    },
    {
        key: "3",
        screen_name: "Classic Theater Hall",
        theater: "Broadway Cinema, NY",
        total_seats: 300,
        available_seats: 200,
        show_time: "2024-10-05 19:00",
        status: "Available",
    },
    {
        key: "4",
        screen_name: "4DX Experience",
        theater: "Coachella Cineplex, CA",
        total_seats: 150,
        available_seats: 10,
        show_time: "2024-09-25 17:45",
        status: "Sold Out",
    },
    {
        key: "5",
        screen_name: "Luxury Recliner Hall",
        theater: "Los Angeles Cinema House, LA",
        total_seats: 120,
        available_seats: 70,
        show_time: "2024-08-10 12:00",
        status: "Available",
    },
    {
        key: "6",
        screen_name: "IMAX 3D",
        theater: "Wembley Grand Cinema, London",
        total_seats: 220,
        available_seats: 30,
        show_time: "2024-07-20 15:00",
        status: "Almost Full",
    },
];
