// MockScreensData.js
export const screensMockData = [
    {
        id: 1,
        screen_name: "Cinema 1",
        venue_name: "Grand Cineplex",
        place_name: "Downtown Mall",
        screen_type: "standard",
        capacity: 120,
        available_seats: 98,
        is_active: true,
        description: "Standard screening room with comfortable seating and digital projection",
        seat_structure_id: 1,
        ticket_structure_id: 1,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop"],
        screen_technology: "digital",
        audio_system: "standard",
        available_times: ["morning", "afternoon", "evening"]
    },
    {
        id: 2,
        screen_name: "IMAX Experience",
        venue_name: "Grand Cineplex",
        place_name: "Downtown Mall",
        screen_type: "imax",
        capacity: 250,
        available_seats: 172,
        is_active: true,
        description: "Premium IMAX theater featuring crystal-clear digital projection and immersive sound",
        seat_structure_id: 2,
        ticket_structure_id: 2,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop", "audio_description"],
        screen_technology: "laser",
        audio_system: "dolby_atmos",
        available_times: ["afternoon", "evening", "night"]
    },
    {
        id: 3,
        screen_name: "VIP Lounge",
        venue_name: "Grand Cineplex",
        place_name: "Downtown Mall",
        screen_type: "vip",
        capacity: 50,
        available_seats: 32,
        is_active: true,
        description: "Luxury viewing experience with reclining seats and in-theater dining service",
        seat_structure_id: 3,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair"],
        screen_technology: "laser",
        audio_system: "dolby_atmos",
        available_times: ["evening", "night"]
    },
    {
        id: 4,
        screen_name: "4DX Theater",
        venue_name: "Grand Cineplex",
        place_name: "Downtown Mall",
        screen_type: "4dx",
        capacity: 90,
        available_seats: 65,
        is_active: true,
        description: "4D cinematic experience with motion seats and environmental effects",
        seat_structure_id: 2,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: [],
        screen_technology: "digital",
        audio_system: "dts",
        available_times: ["afternoon", "evening"]
    },
    {
        id: 5,
        screen_name: "Screen 1",
        venue_name: "City Cinema",
        place_name: "City Center",
        screen_type: "standard",
        capacity: 180,
        available_seats: 156,
        is_active: true,
        description: "Main theater screen with stadium seating",
        seat_structure_id: 1,
        ticket_structure_id: 1,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop"],
        screen_technology: "digital",
        audio_system: "standard",
        available_times: ["morning", "afternoon", "evening"]
    },
    {
        id: 6,
        screen_name: "Screen 2",
        venue_name: "City Cinema",
        place_name: "City Center",
        screen_type: "3d",
        capacity: 150,
        available_seats: 124,
        is_active: true,
        description: "3D-capable screen with upgraded sound system",
        seat_structure_id: 1,
        ticket_structure_id: 2,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair"],
        screen_technology: "digital",
        audio_system: "dolby_atmos",
        available_times: ["afternoon", "evening", "night"]
    },
    {
        id: 7,
        screen_name: "Gold Class",
        venue_name: "City Cinema",
        place_name: "City Center",
        screen_type: "vip",
        capacity: 40,
        available_seats: 28,
        is_active: false,
        description: "Premium screening room with full recliner seats and butler service",
        seat_structure_id: 3,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair"],
        screen_technology: "laser",
        audio_system: "dolby_atmos",
        available_times: ["evening", "night"]
    },
    {
        id: 8,
        screen_name: "The Dome",
        venue_name: "Starlight Cinema",
        place_name: "West Plaza",
        screen_type: "imax",
        capacity: 300,
        available_seats: 248,
        is_active: true,
        description: "Massive dome screen with state-of-the-art projection technology",
        seat_structure_id: 2,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop", "audio_description"],
        screen_technology: "laser",
        audio_system: "dolby_atmos",
        available_times: ["morning", "afternoon", "evening", "night"]
    },
    {
        id: 9,
        screen_name: "Theater 1",
        venue_name: "Starlight Cinema",
        place_name: "West Plaza",
        screen_type: "standard",
        capacity: 140,
        available_seats: 112,
        is_active: true,
        description: "Standard cinema with upgraded seating",
        seat_structure_id: 1,
        ticket_structure_id: 1,
        has_reserved_seating: false,
        accessibility_features: ["wheelchair"],
        screen_technology: "digital",
        audio_system: "standard",
        available_times: ["morning", "afternoon", "evening"]
    },
    {
        id: 10,
        screen_name: "Theater 2",
        venue_name: "Starlight Cinema",
        place_name: "West Plaza",
        screen_type: "4dx",
        capacity: 80,
        available_seats: 48,
        is_active: false,
        description: "Immersive 4DX experience with environmental effects",
        seat_structure_id: 2,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: [],
        screen_technology: "digital",
        audio_system: "dts",
        available_times: ["afternoon", "evening"]
    },
    {
        id: 11,
        screen_name: "Screen A",
        venue_name: "Riverside Multiplex",
        place_name: "Riverside Mall",
        screen_type: "standard",
        capacity: 160,
        available_seats: 138,
        is_active: true,
        description: "Standard screening room with digital projection",
        seat_structure_id: 1,
        ticket_structure_id: 1,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop"],
        screen_technology: "digital",
        audio_system: "standard",
        available_times: ["morning", "afternoon", "evening", "night"]
    },
    {
        id: 12,
        screen_name: "Screen B",
        venue_name: "Riverside Multiplex",
        place_name: "Riverside Mall",
        screen_type: "3d",
        capacity: 150,
        available_seats: 124,
        is_active: true,
        description: "3D-capable theater with upgraded seating",
        seat_structure_id: 1,
        ticket_structure_id: 2,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair"],
        screen_technology: "digital",
        audio_system: "dolby_atmos",
        available_times: ["afternoon", "evening", "night"]
    }
];

// This could be used in the add/edit form for template selection
export const screenTemplates = [
    {
        id: 1,
        name: "Standard Theater",
        screen_type: "standard",
        capacity: 150,
        seat_structure_id: 1,
        ticket_structure_id: 1,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop"],
        screen_technology: "digital",
        audio_system: "standard",
    },
    {
        id: 2,
        name: "IMAX Theater",
        screen_type: "imax",
        capacity: 250,
        seat_structure_id: 2,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair", "hearing_loop"],
        screen_technology: "laser",
        audio_system: "dolby_atmos",
    },
    {
        id: 3,
        name: "VIP Theater",
        screen_type: "vip",
        capacity: 50,
        seat_structure_id: 3,
        ticket_structure_id: 3,
        has_reserved_seating: true,
        accessibility_features: ["wheelchair"],
        screen_technology: "laser",
        audio_system: "dolby_atmos",
    }
];

// Venue data that could be used in the venue selection form
export const venuesMockData = [
    {
        id: 1,
        name: "Grand Cineplex",
        place_id: 1,
        place_name: "Downtown Mall",
        screens_count: 4
    },
    {
        id: 2,
        name: "City Cinema",
        place_id: 2,
        place_name: "City Center",
        screens_count: 3
    },
    {
        id: 3,
        name: "Starlight Cinema",
        place_id: 3,
        place_name: "West Plaza",
        screens_count: 3
    },
    {
        id: 4,
        name: "Riverside Multiplex",
        place_id: 4,
        place_name: "Riverside Mall",
        screens_count: 2
    }
];

// Place/Location data that could be used in the place selection form
export const placesMockData = [
    {
        id: 1,
        name: "Downtown Mall",
        city: "New York",
        country: "USA"
    },
    {
        id: 2,
        name: "City Center",
        city: "Los Angeles",
        country: "USA"
    },
    {
        id: 3,
        name: "West Plaza",
        city: "Chicago",
        country: "USA"
    },
    {
        id: 4,
        name: "Riverside Mall",
        city: "Miami",
        country: "USA"
    }
];