export const ApiConstant = {
  API_BASE_URL: "https://uat-tickets2me.mitetechnology.com",
  CATEGORY_URL: "/api/v1/events/secured/category",
  USER_URL: "/api/v1/auth/secured/users",
  SUB_CATEGORY_URL: "/api/v1/events/secured/subcategory",
  PLACE_WITH_COUNTRY_URL: "/api/v1/location/secured/place_with_country",
  PLACE_URL: "/api/v1/location/secured/place",
  EDIT_PLACE_URL: "/api/v1/location/secured/edit_place",
  EDIT_VENUE_URL: "/api/v1/location/secured/edit_venue",
  VENUE_URL: "/api/v1/location/secured/venue",
  COUNTRY_DETAILS_URL: "/api/v1/location/secured/country/details",
  EVENT_URL: "/api/v1/events/secured/event",
  EVENT_DETAILS_URL: "/api/v1/events/secured/events/detail",
  EDIT_EVENT_URL: "/api/v1/events/secured/edit_event",
  OFFER_URL: "/api/v1/offers/secured/offers",
  COUPON_URL: "/api/v1/offers/secured/coupons",
  TICKET_URL: "/api/v1/tickets/secured/ticketstructure",
  AVAILABLE_TICKET_TYPE_URL: "/api/v1/events/secured/available_types",
  SCHEDULE_URL: "/api/v1/events/secured/schedules",
  STATICS_EVENT_LIST: "/api/v1/statics/secured/events",
  STATICS_USER_LIST: "/api/v1/statics/secured/users",
  STATICS_SCHEDULES_LIST: "/api/v1/statics/secured/schedules",
};
