export const ApiConstant = {
  API_BASE_URL: "https://uat-tickets2me.mitetechnology.com",
  CATEGORY_URL: "/api/v1/events/secured/category",
  SINGLE_CATEGORY_URL: "/api/v1/events/secured/singlecategory",
  USER_URL: "/api/v1/auth/secured/users",
  REGISTER_USER_URL: "/api/v1/auth/secured/register",
  ROLES_URL: "/api/v1/auth/secured/role",
  SUB_CATEGORY_URL: "/api/v1/events/secured/subcategory",
  SUB_SINGLE_CATEGORY_URL: "/api/v1/events/secured/singlesubcategory",
  PLACE_WITH_COUNTRY_URL: "/api/v1/location/secured/place_with_country",
  PLACE_URL: "/api/v1/location/secured/place",
  EDIT_PLACE_URL: "/api/v1/location/secured/edit_place",
  EDIT_VENUE_URL: "/api/v1/location/secured/edit_venue",
  VENUE_URL: "/api/v1/location/secured/venue",
  SINGLE_VENUE_URL: "/api/v1/location/secured/singlevenue",
  SINGLE_PLACE_URL: "/api/v1/location/secured/singleplace",
  COUNTRY_DETAILS_URL: "/api/v1/location/secured/country/details",
  EVENT_URL: "/api/v1/events/secured/event",
  EVENT_VALIDATION_URL: "/api/v1/events/secured/validation_event",
  EVENT_DETAILS_URL: "/api/v1/events/secured/events/detail",
  EDIT_EVENT_URL: "/api/v1/events/secured/edit_event",
  OFFER_URL: "/api/v1/offers/secured/offers",
  COUPON_URL: "/api/v1/offers/secured/coupons",
  TAX_URL: "/api/v1/location/secured/taxes",
  AVAILABLE_TAX_CATEGORY_URL: "/api/v1/location/secured/available_tax_category",
  TICKET_URL: "/api/v1/tickets/secured/ticketstructure",
  AVAILABLE_TICKET_TYPE_URL: "/api/v1/events/secured/available_types",
  SCHEDULE_URL: "/api/v1/events/secured/schedules",
  STATICS_EVENT_LIST: "/api/v1/statics/secured/events",
  STATICS_USER_LIST: "/api/v1/statics/secured/users",
  STATICS_SCHEDULES_LIST: "/api/v1/statics/secured/schedules",
  ISSUE_LIST_URL: "/api/v1/issue/secured/issues",
  ISSUE_DETAILS_URL: "/api/v1/issue/secured/issues/details",
  ISSUE_STATUS_UPDATE_URL: "/api/v1/issue/secured/issues/status",
  ISSUE_CLOSE_URL: "/api/v1/issue/secured/issues/close",
  ISSUE_REASSIGN_URL: "/api/v1/issue/secured/issues/assign",
  ISSUE_REASSIGN_COMMENT_URL: "/api/v1/issue/secured/issues/comment",

  // ADVERTISEMENT ENDPOINTS

  ADVERTISEMENT_CATEGORY_URL: "/api/v1/banners/secured/bannercategory",
  ADVERTISEMENT_CATEGORY_UPDATE_URL: "/api/v1/banners/secured/bannercategoryupdate",

};
