export const TextConstants = {
  Confirm_Action: "Confirm Action",
  WantToProceed: "Are you sure you want to proceed?",
  CannotProceed: "You cannot proceed. Please fix the warnings manually.",
  StatusUpdatedSuccess: "Status updated successfully.",
  ItemAddedSuccessfully: "Item added successfully.",
  StatusUpdateCanceled: "Status update canceled.",
  ItemAddCanceled: "Item addition canceled.",
  StatusUpdateError: "Error updating the status.",
  ErrorLoadingItem: "Error loading the item for editing.",
  ProceedButton: "Proceed",
  BackButton: "Back",
  ErrorSubmittingItem: "Error submitting the item. Please try again.",
  NoItemSelected: "No item selected for confirmation.",
  FailedToConfirmItem: "Failed to confirm the item.",
  ConfirmationError: "An error occurred during confirmation.",
  ConfirmItemDetails: "Confirm Item Details",
  ConfirmItem: "Confirm Item",
  Cancel: "Cancel",
  Pending: "pending",
};
